### ISSUE TITLE
Improvement of the documentation

### ISSUE THREAD

**Issue by quark67** [selvamtech08/affilauthor#1]
Instead of using bitmap images on page 2 of the documentation:

```latex
\noindent\includegraphics[width=\textwidth]{authorname_sampleimage.png}
```

and

```latex
\noindent\includegraphics[width=\textwidth]{affiliations_sampleimage.png}
```

(see lines 65 and 69)

it is better to include the pdf and cropping it, so you keep the vectorized quality.

Use the `trim` and `clip` option of `\includegraphics`, like:

```latex
\includegraphics[clip, trim=left bottom right top, width=\textwidth]{file.pdf}
```

where left, bottom, right and top are lenght (for exemple, 3cm).

Note: using this trick, the whole file.pdf is included, it's only a trick to display a part of the included PDF file, but you can retrieve the whole content of the included PDF file in the pdf file outputted by LaTeX (see the comment from Martin Sharrer at https://tex.stackexchange.com/questions/25806/how-can-i-crop-included-pdf-documents#comment273296_94424).

You can also use the `pdfcrop` CLI command (see https://ctan.org/pkg/pdfcrop) to create cropped versions of the PDF. Use negative values (given in the bp unit, 1 cm is approx. 28.35 bp) for remove space arround the content you will include. For example:

```
pdfcrop --clip --margins '-30 -30 -30 -30' input.pdf output.pdf
```

and then use the usual `\includegraphics[width=\textwidth]{output.pdf}`.

**Comment by selvamtech08** [comment]
Thanks for such valuable suggestion. At the time of document preparation, i have little confusion about which image format is preferable for package submission. I take a note and do the changes.

**Comment by selvamtech08** [comment]
image format changed as suggested(using pdf format).
