### ISSUE TITLE
Missing affilauthor-doc.tex in this repository

### ISSUE THREAD

**Issue by quark67** [selvamtech08/affilauthor#2]
The file http://mirrors.ctan.org/macros/latex/contrib/affilauthor/affilauthor-doc.tex is missing in this repository.

Also are missing 
http://mirrors.ctan.org/macros/latex/contrib/affilauthor/affiliations_sampleimage.png and 
http://mirrors.ctan.org/macros/latex/contrib/affilauthor/authorname_sampleimage.png

but see https://github.com/selvamtech08/affilauthor/issues/1 (so you don't need to include .png files, but instead a .pdf file).

**Comment by selvamtech08** [comment]
Will updates the missing files with #1 fix.

**Comment by selvamtech08** [comment]
Doc file now copied.

**Comment by selvamtech08** [comment]
doc file updated.
